### ISSUE TITLE
Please clarify the relationship between this GitHub project and colined.com.

### ISSUE THREAD

**Issue by moriyoshi** [damat/ImageAboveText#2]
First, thank you for the great plugin.  It just worked and saved my life.

While none seems to be wrong, it would more soothe me if the following points were made clear.

* The privacy policy and TaC links in the [G Suite marketplace page](https://gsuite.google.com/marketplace/app/image_above_text_for_google_docs/366452405248) point to https://colined.com/privacy.html and https://colined.com/terms.html respectively, however the rest of the links direct to this GitHub project page which appears to indicate no affiliation with the company. 
* Neither this product isn't listed in colines.com.

**Comment by damat** [comment]
Hello @moriyoshi,

Sorry for the late reply, missed this notification. 

We are Colined, vendor on the Atlassian Marketplace. We also have three GSuite add-ons as pet/test projects. We make zero profits on GSuite Marketplace, and that's something unlikely to change any time soon. In order to keep it simple, we linked them to docs we already had. Sorry for the confusion.
